resolver: lts-10.9
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True
    buildWebsite:  True

packages:
  - '.'

extra-deps:
  - 'pandoc-citeproc-0.14.1.5'

nix:
  enable: false
  packages:
    - zlib
